AWSTemplateFormatVersion: 2010-09-09
Description: 'Create a s3 bucket, configured for static web hosting'

Parameters:
  BucketName:
    Type: String
  IndexDocument:
    Type : String
  ErrorDocument:
    Type : String
    

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
       IndexDocument: !Ref IndexDocument
       ErrorDocument: !Ref ErrorDocument
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  S3BUCKETPOLICY:
     Type: AWS::S3::BucketPolicy
     Properties: 
       Bucket: !Ref S3Bucket
       PolicyDocument:
        Version: '2012-10-17'
        Statement:
         - Action:
            - 's3:GetObject'
           Effect: Allow
           Principal: "*"
           Resource: !Sub arn:aws:s3:::${S3Bucket}/*